[2025-02-25T15:34:14.749+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dvc_pipeline.evaluate_model manual__2025-02-25T15:30:32.743321+00:00 [queued]>
[2025-02-25T15:34:14.766+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dvc_pipeline.evaluate_model manual__2025-02-25T15:30:32.743321+00:00 [queued]>
[2025-02-25T15:34:14.766+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-02-25T15:34:14.789+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): evaluate_model> on 2025-02-25 15:30:32.743321+00:00
[2025-02-25T15:34:14.799+0000] {standard_task_runner.py:60} INFO - Started process 317 to run task
[2025-02-25T15:34:14.806+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dvc_pipeline', 'evaluate_model', 'manual__2025-02-25T15:30:32.743321+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline_dag.py', '--cfg-path', '/tmp/tmpt4x72ut6']
[2025-02-25T15:34:14.817+0000] {standard_task_runner.py:88} INFO - Job 101: Subtask evaluate_model
[2025-02-25T15:34:14.844+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-02-25T15:34:14.917+0000] {task_command.py:423} INFO - Running <TaskInstance: dvc_pipeline.evaluate_model manual__2025-02-25T15:30:32.743321+00:00 [running]> on host e4b564b54e23
[2025-02-25T15:34:15.121+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dvc_pipeline' AIRFLOW_CTX_TASK_ID='evaluate_model' AIRFLOW_CTX_EXECUTION_DATE='2025-02-25T15:30:32.743321+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-25T15:30:32.743321+00:00'
[2025-02-25T15:34:23.799+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-02-25T15:34:23.831+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dvc_pipeline, task_id=evaluate_model, execution_date=20250225T153032, start_date=20250225T153414, end_date=20250225T153423
[2025-02-25T15:34:23.889+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-02-25T15:34:23.991+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
